### PR TITLE
Updating squirrel_dynamic_filter_msgs

### PR DESCRIPTION
**Pull request by ayushais**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
this requires a pull request for squirrel_nav

**Comment by ayushais** [comment]
Federico will send a pull request later today for squirrel_nav update from our side.

**Comment by ipa-nhg** [comment]
@ayushais @federico-b is this pull request still needed? it is adding again the packages:

- squirrel_rgbd_mapping_msgs
- squirrel_localizer_msgs
- squirrel_sketch_interface_msgs

**Comment by ayushais** [comment]
It is not needed anymore

**Pull request closed without merging**
