### PR TITLE
added gazebo controllers for the shell

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by tpatten** [comment]
@ipa-nhg @mzillich: I tested the gazebo simulation and could move the arm and base with rqt. However, there is a problem. Some of the arm joints also move the base. arm_joint1 moves base in x direction, arm_joint2 moves base in y direction and arm_joint3 moves base in z direction. arm_joint4 and 5 are ok.

**Comment by tpatten** [comment]
@edith-langer also tried and had the same issue. Strangely, @lokalmatador ran the simulation and did not have this problem. Moving the arm did not move the base for Philip.

**Comment by ghost** [comment]
As just documented in the mail, in my case this may be related to these errors 

`ERROR: cannot launch node of type [twist_mux/twist_mux]: twist_mux
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/lokalmatador/Work/ROS/squirrel_test
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/inidigo/stacks
ERROR: cannot launch node of type [twist_mux/twist_marker]: twist_mux
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/lokalmatador/Work/ROS/squirrel_test
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/inidigo/stacks`

when executing

`roslaunch robotino_bringup_sim robot.launch robot:=tuw-robotino2`

**Comment by ipa-nhg** [comment]
@lokalmatador please call `sudo apt-get install ros-indigo-twist-mux`
or better:
```
cd ~/catkin_ws
rosdep install --from-path src -i -y -r
```

@tpatten basically I am using the BaseController class (the same than the real robot) to control the base on simulation https://github.com/squirrel-project/squirrel_driver/blob/indigo_dev/squirrel_control/src/ArmControllerSim.cpp , but could be that the order of the joint chain is wrong, I will check it.

**Comment by ghost** [comment]
Already did an upgrade when last testing it. Did not change anything. Right now I'm in the train. Let's see in Vienna.

**Comment by ipa-nhg** [comment]
@tpatten  I don't know why but rqt command the chain `[ arm_joint1, arm_joint2, arm_joint3, arm_joint4, arm_joint5, base_jointx, base_jointy, base_jointz]` instead of `[base_jointx, base_jointy, base_jointz, arm_joint1, arm_joint2, arm_joint3, arm_joint4, arm_joint5]`  , this PR https://github.com/squirrel-project/squirrel_driver/pull/147 should solve the problem please test!

**Comment by tpatten** [comment]
@ipa-nhg Yes it works with this fix. I can move the arm joints without them also moving the base.

**Pull request merged**
