### PR TITLE
update the stl base collision

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@mzillich please test and give me a feedback

**Comment by tpatten** [comment]
Thank you. @philkark are you able to try this out in simulation?

**Comment by philkark** [comment]
I have checked the modell and compared it to the real visualized robot and would say it might be too restrictive. In my opinion, the planner should not use the full mesh for collision checking, because that would be too inefficient during planning. the approximated half-cylinder from before was probably the best compromise, however, I would increase the size a little bit to encase the whole shell structure but, if possible, go as little beyond as possible.

**Comment by ipa-nhg** [comment]
@philkark @tpatten check this comparison(take some time to load)

https://github.com/squirrel-project/squirrel_common/pull/256/commits/bb9e00c00533b8d7e8cc4b645d36e002d114b19e#diff-4d7d4b40b0bd0adfb2b9c1e3448b57d9

enough or the cylinder should be bigger?

**Comment by tpatten** [comment]
That actually looks very nice. Even though the corners extend beyond the cylinder, I think it will be ok.

**Comment by philkark** [comment]
This looks very nice! Thank you very much, I will integrate it into my planner as well and then we can check how the plans will perform.

**Comment by ipa-nhg** [comment]
I will merge it because for sure this one is better than the actual cylinder and you can use the upstream repository to test the model.

Please let me know if it is still not good enough!

**Pull request merged**
