### PR TITLE
Arm review

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Thanks @philkark 
@philkark @lokalmatador @mzillich please review

**Comment by ghost** [comment]
LGTM though cannot test. But I guess it's fine.

**Comment by ipa-nhg** [comment]
could this be tested on tuw-robotino???

**Comment by mzillich** [comment]
will do. currently the shell is not fully assembled yet.

**Comment by tpatten** [comment]
Tested and arm movement seems correct. Although, when moving arm_joint1 the arm moved in the opposite direction to the labels we drew on the arm a long time ago in Freiburg. I'm not sure which one is supposed to be correct? Any ideas?

More importantly, there is an issue with the base. Using rqt, when I changed values for base_jointx the robot moved along the y-axis. Likewise, changing the values for base_jointy the robot moved along the x-axis. This is definitely a problem! I thought only things to do with the arm changed??

**Comment by bajo** [comment]
@tpatten I would go with the implementation. The arrows on the arm were mainly for us while moving the arm manually. Their orientation is still based on the former implementation (kukadu) and no longer reflect the currently used on. The easiest is to redraw the +/- direction on the arm.

**Comment by tpatten** [comment]
@bajo thanks. I figured it was just an arbitrary assignment.

Then the only issue is the base x and y before this can be merged.

**Comment by tpatten** [comment]
I tested this just now in simulation and the robot moves as expected. Base_jointx -> moves along x-axis, base_jointy -> moves along y-axis. It is only with the real robot.

**Comment by tpatten** [comment]
I also rolled back to the current master. It seems that this was an existing issue unrelated to this pull request. Is it safe to merge this @ipa-nhg?

**Comment by ipa-nhg** [comment]
merge conflict solved. But before merge I need a consensus between uibk, tuw and alu-fr about the motor direction of the joint 1, positive or negative? https://github.com/ipa-nhg/squirrel_common/blob/9aa66f1dcea86471c54a20cadc42e0946c1d40c2/robotino_description/urdf/arm.urdf.xacro#L35 

@mzillich @tpatten @bajo @lokalmatador @federico-b

**Comment by ghost** [comment]
What does the change imply?

**Comment by tpatten** [comment]
One of the changes here was made because of the inconsistency between the real robot and the simulator as pointed out by @philkark. If both models are the same then it should not make a difference. Maybe its best to define the direction the way @philkark uses it in the arm planner.

**Comment by bajo** [comment]
@lokalmatador I think it is just the fact that with the old implementation the direction of the first arm joint was inverted to what it is now. We marked the orientation on the arm to make it easier to move the arm in the correct direction when moving it manually (rqt and similar tools). As this was purely to guide us I think we should just stick to the current implementation, and consistently put it on all robots with an arm. 

@ipa-nhg or was there any other reason to change the orientation now?

**Comment by ghost** [comment]
Yep, as @bajo says, let's make it consistent as long as it does not yield problems.

**Comment by ipa-nhg** [comment]
@philkark sent me a mail after the integration meeting with the following information:
```

"squirrel_common/robotino_description/urdf/arm.urdf.xacro", the robot
model has reversed motor directions for joints 1 and 4, so we needed to
reverse the motor directions in order to have the robot model align with
the real robot:

<joint name="${name}joint1" type="revolute">
   ...
   <axis xyz="0 -1 0" />
</joint>

and

<joint name="${name}joint4" type="revolute">
   ...
   <axis xyz="0 -1 0" />
</joint>
```

I also know that when the  alu-fr arm was working they had to modify locally the axis direction because their hardware didn't correspond to the default description. If I merge this and  the motor direction of the first joint is wrong, we will break the arm testing the planning software. Please confirm with rqt that this description is right for **ALL** the real arms.

**Comment by philkark** [comment]
I would like to confirm this. I have tested this with Michael during the latest review meeting in Vienna and both arm_joint1 and arm_joint4 needed to have axis direction of "0 -1 0".

**Comment by tpatten** [comment]
Here is the Vienna robot with joint1 set to -1.0 and joint4 set to 1.0. It is the same as in simulation. Can Innsbruck and Freiburg confirm that their robots are the same.
robot_joints

**Comment by ghost** [comment]
We shipped 2 of our arm's motors to UIBK. Do not consider our arm by now.

**Comment by ipa-nhg** [comment]
@lokalmatador please feedback

**Comment by ghost** [comment]
No chance to test so far, as we were busy with organizing some events and also still face the problem of removing the screws currently affixed to the motor for holding the metal plate that connects to the fifth motor (remember we only got a working fourth motor from Freiburg). As these screws are quite worn and firmly screwed-in we're still looking for a way to unscrew them. Hopefully today brings some progress. Also, replacing our fourth motor with Freiburg's fourth (making our fourth the fifth) does not solve the issue as also for our fourth motor, we face that "unscrewing" issue.

**Comment by ipa-nhg** [comment]
The only working robot is TUW and there the motors directions are +1  (@tpatten thanks a lot for  the screenshots) I suggest keep this version. 
Once the UIBK and ALU-FR hardware is fixed please test the motor directions carefully.

**Comment by tpatten** [comment]
@ipa-nhg are the joints supposed to be "0 -1 0" as @philkark suggested? The main branch that merged this pull request still has these joints as "0 1 0". Maybe it was confusing, but in my previous comment I was referring to joints with values "0 -1 0".

**Comment by ipa-nhg** [comment]
oh, sorry I understood you tested the arm with the squirrel-project version, I will fix it now!!

**Comment by ipa-nhg** [comment]
--> https://github.com/squirrel-project/squirrel_common/pull/239

**Comment by ghost** [comment]
Checked on UIBK's robot and all is fine!

**Pull request merged**
