### PR TITLE
Reference frame for kclhand

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
the old  hand_base_link is now kclhand_base_link, and the new hand_base_link is pointing upwards.

@edith-langer  let me know if thie ok for you, @lokalmatador may you have to update the tip_link parameter to kclhand_base_link https://github.com/squirrel-project/squirrel_manipulation/blob/6fa81336fc133ef3ad3909965394f3a390d08e4d/squirrel_ptp_server/launch/ptp_metahand.launch#L3

**Comment by ghost** [comment]
yeah, I thought so; but this should be easily doable by switching axis values; maybe  @mzillich or @edith-langer can check this, if this does not fix it, I'll have a look at it

**Comment by edith-langer** [comment]
Do you think it is save to change the original name? Maybe we should leave the old link as hand_base_link and give the new one a different name? 

I use the hand_base_link to add 10 cm to the z-direction. Which should be approximately the position of the object in hand. For the softhand I could use the hand_palm_link, but there is no equivalent for kcl_hand.

**Comment by ipa-nhg** [comment]
if you use the hand_palm_link for the softhand , I can setup the same name for kclhand to define the upwards link.

and for hand_base_link keep the kcl version.

**Comment by edith-langer** [comment]
We can do that, but for the kclhand the palm_link should not have the same position as the hand_base_link but should be also shifted around 10 cm towards the fingers. 

If you think that does not make sense, I can also use the hand_base_link. I just wanted to make sure that it is ok to rename the original frame and not the new one.

**Comment by ipa-nhg** [comment]
@edith-langer I will create the link just for you, you can choose the name and the position :smile: 

@mzillich To modify the kinematic of the hand should be kcl involved , the model, kinematic and driver was by kcl developed, I don't want to modify anything because I don't know how a kinematic modification could affect to the driver and the calibration.

**Comment by ipa-nhg** [comment]
@edith-langer do you mean this or 10cm up?


hand_palm_link

**Comment by edith-langer** [comment]
Looks good! But I think the names should be switched? The upper one should be hand_palm_link, shouldn't it? In your picture the hand_palm_link is the original hand_base_link?

**Comment by ipa-nhg** [comment]
No, hand_base_link has the original position, if you check the changes https://github.com/squirrel-project/squirrel_common/pull/186/files I only added the hand_palm_link. Then the previous version was right? with hand_palm_link and base_hand_link on the same position?

**Comment by edith-langer** [comment]
Ah, sorry. You are right!
Can you please move hand_palm_link to "hand_base_link.y + 0.1"
Thanks!

**Comment by ipa-nhg** [comment]
done!

**Pull request merged**
